name: Pipeline

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

  strategy:
    matrix:
      node-version: [18.x]

  steps:
   - name: use node
     uses: npm actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: tests
      run: npm run test
    - name: build
      run: npm run build
